name: CI
on:
  pull_request:
    branches:
      - main
      - features
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  # Skip intermediate builds for the same PR/branch to save resources
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'      # Automatically targets the latest stable 1.x release
          - 'lts'    # Long-Term Support version
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        arch:
          - x64

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia dependencies
        uses: julia-actions/cache@v2

      # TODO: Register Parallel Gradient and QuantumNaturalGradient. The rm() command is only necessary because the develop() command doesn't overwrite existing entries in the manifest, so if we register the packages, we can remove the rm() command and just use Pkg.add() to install the dependencies.
      - name: Set up project and run tests
        run: |
          julia --project=. -e '
            using Pkg
            
            Pkg.rm("ParallelGradient")
            Pkg.rm("QuantumNaturalGradient")

            Pkg.develop([
              PackageSpec(url="https://github.com/NeTeNeSyQuMa/ParallelGradient.jl"),
              PackageSpec(url="https://github.com/NeTeNeSyQuMa/QuantumNaturalGradient.jl")
            ])

            Pkg.instantiate()

            Pkg.test()
          '